name: eksouvan
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  equatable: ^2.0.3
  get_it: ^7.2.0
  injectable: ^1.5.3
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  internet_connection_checker: ^0.0.1+4
  logger: ^1.1.0
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  retrofit: ^3.0.1+1
  dartz: ^0.10.1
  flutter_bloc: ^8.0.1
  retrofit_generator: ^4.0.1
  injectable_generator: ^1.5.3
  firebase_core: ^1.19.1
  easy_localization: ^3.0.1
  cloud_firestore: ^3.2.1
  flutter_form_builder: ^7.3.1
  firebase_auth: ^3.4.1
  date_time_picker: ^2.1.0
  uuid: ^3.0.6
  modal_bottom_sheet: ^2.1.0
  printing: ^5.9.2
  pdf: ^3.8.2
  flutter_svg: ^1.1.3
  flutter_switch: ^0.3.2
  firebase_admin: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/translations/
  # example:
  fonts:
    - family: NotoSansLao
      fonts:
        - asset: assets/fonts/NotoSansLao-Regular.ttf
        - asset: assets/fonts/NotoSansLao-Bold.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

